name: Install dependencies
description: Prepare node, pnpm and all dependencies
inputs:
  before-install:
    description: before install script
    required: false
    default: ''

runs:
  using: composite
  steps:
    #! Determine versions
    - name: Determine versions
      id: determine-versions
      shell: bash
      run: |
        echo "nodeVersion=$(jq -r .volta.node package.json)" >> $GITHUB_OUTPUT

    #! Node
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.determine-versions.outputs.nodeVersion }}
        cache: pnpm

    #! Nx
    - name: Cache nx build setup
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-nx-

    #! Clear old nx cache
    - name: Clear old nx cache
      uses: ./.github/actions/clear-old-nx-cache
      with:
        size-in-mb: 10

    #! Before install
    - name: Before install
      if: ${{ inputs.before-install != '' }}
      shell: bash
      run: ${{ inputs.before-install }}

    #! Install
    - name: Install Dependencies
      shell: bash
      run: pnpm i
