$schema: https://unpkg.com/markdownlint-cli2@latest/schema/markdownlint-cli2-config-schema.json

globs:
  - '**/*.{md,markdown}'
ignores:
  - '**/coverage'
  - '**/dist'
  - '**/node_modules'
  - '**/.nx'

config:
  extends: node_modules/markdownlint/style/prettier.json
  no-inline-html: false
  no-duplicate-heading: false
