$schema: https://unpkg.com/markdownlint-cli2@latest/schema/markdownlint-cli2-config-schema.json

globs:
  - '**/*.{md,markdown}'
ignores:
  - '**/.nx'
  - '**/coverage'
  - '**/dist'
  - '**/node_modules'
  # ignore projects that have custom lint and test scripts
  - apps
  - templates

config:
  extends: node_modules/markdownlint/style/prettier.json
  no-inline-html: false
  no-duplicate-heading: false
