compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

globalFolder: .yarn/berry

nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  #! changesets-generate-dependencies-changesets
  '@actions/github@*':
    dependencies:
      undici: '*'

  #! config-eslint
  eslint-plugin-import-x@*:
    peerDependencies:
      tslib: '*'
  eslint-plugin-perfectionist@*:
    dependencies:
      '@typescript-eslint/types': '*'
  eslint-processor-vue-blocks@*:
    dependencies:
      '@vue/compiler-sfc': '*'
