compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

globalFolder: .yarn/berry

nodeLinker: pnp

packageExtensions:
  "@actions/github@*":
    dependencies:
      undici: "*"
  eslint-plugin-import-x@*:
    dependencies:
      tslib: "*"
  eslint-plugin-perfectionist@*:
    dependencies:
      "@typescript-eslint/types": "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
