compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

globalFolder: .yarn/berry

nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.2.2.cjs

packageExtensions:
  eslint-plugin-perfectionist@*:
    dependencies:
      '@typescript-eslint/types': '*'
  eslint-plugin-import-x@*:
    dependencies:
      tslib: '*'
  '@actions/github@*':
    dependencies:
      undici: '*'
