name: 💾 Clear old nx cache
description: Clear old nx cache

inputs:
  size-in-mb:
    description: Cache size in MB
    required: true
  cache-directory:
    description: The path to the NX cache directory
    default: .nx/cache

runs:
  using: composite
  steps:
    # https://github.com/nrwl/nx/issues/2883#issuecomment-1449078285
    #! Clear old nx cache
    - name: 💾 Clear old nx cache
      shell: bash
      env:
        SIZE: ${{ inputs.size-in-mb }}
        NX_CACHE_DIR: ${{ inputs.cache-directory }}
      run: |
        chmod +x .github/scripts/clear-old-nx-cache.sh
        .github/actions/clear-old-nx-cache/script.sh
