name: 'Main'

on: [push, pull_request]

env:
  TURBO_CACHE_DIR: .turbo

jobs:
  #! ----- ----- ----- Build ----- ----- ----- !#
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      #! Checkout
      - name: Checkout
        uses: actions/checkout@v4

      #! Install dependencies
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      #! Build
      - name: Build
        run: yarn build

      #! Lint
      - name: Lint
        run: yarn lint

      #! Test
      - name: Test
        run: yarn test

      #! Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/release' }}
        with:
          name: build-artifact
          path: |
            packages/*/dist/
            scripts/*/dist/
          if-no-files-found: error

  #! ----- ----- ----- Release ----- ----- ----- !#
  release:
    name: Prepare release pull request
    needs: build
    if: ${{ github.ref == 'refs/heads/release' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      #! Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      #! Install dependencies
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      #! Create release pull request
      - name: Create release pull request
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          branch: main
          version: yarn changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #! ----- ----- ----- Build with pnp ----- ----- ----- !#
  build_pnp:
    name: Build and test with yarn pnp
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-pnp
      cancel-in-progress: true
    steps:
      #! Checkout
      - name: Checkout
        uses: actions/checkout@v4

      #! Prepare branch
      - name: Prepare branch
        run: |
          git branch feat/yarn-pnp -f
          git checkout feat/yarn-pnp

      #! Install dependencies
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-linker: 'pnp'

      #! Yarn pnp
      - name: Commit & push
        run: |
          git config --global user.name 'culur'
          git config --global user.email 'culur.net@gmail.com'
          git add .
          git commit -m "build(package): config yarn pnp"
          git push --set-upstream origin feat/yarn-pnp -f

      #! Build
      - name: Build
        run: yarn build

      #! Lint
      - name: Lint
        run: yarn lint

      #! Test
      - name: Test
        run: yarn test
